### ISSUE TITLE
Update and Get Product is not working

### ISSUE THREAD

**Issue by shahshyam** [ElijahGlover/GeckoApi#1]
Hello, 
I am using your TradeGeecko API, client , it has  issue in GetProduct by Id , Update Item and Delete Item. Issue is due to URL Address. 
API url format should be <Object Type>/Id
ObjecType may be Product, Order and Users etc

**Comment by ElijahGlover** [comment]
Hi shahshyam,

Happy to review and accept a pull request to fix issues found. I had a quick look, it doesn't look like the API spec has moved.

Cheers,
Elijah

**Comment by shahshyam** [comment]
This is curl -X GET -H "Content-type: application/json" -H "Authorization: Bearer <ACCESS_TOKEN>"
https://api.tradegecko.com/products/1
so instead of **protected override string ResourceItemUri { get { return "/products/{id}"; } }** your need to make protected override string ResourceItemUri { get { return "/products/<id value>"; } }

**Comment by ElijahGlover** [comment]
Send a pull request, I don't have time to maintain this library
